### ISSUE TITLE
🚀 [Feature]: My (simple) SSEFiber Package (for featuring on extensions page)

### ISSUE THREAD

**Issue by jsorb84** [gofiber/awesome-fiber#35]
### Feature Description

A very simple package to add SSE support for fiber 

https://github.com/jsorb84/ssefiber
https://pkg.go.dev/github.com/jsorb84/ssefiber

### Code Snippet (optional)

```go
// Example of usage, see package links for more info

package main

import (
"github.com/gofiber"
"github.com/jsorb84/ssefiber"
)

func main() {
  app := fiber.New(...)
  sse := ssefiber.New(app, "/sse")
  channelOne := sse.CreateChannel("Channel One", "/one") // /sse/one
  channelOne.SendEvent("name", "data")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by gaby** [comment]
Wrong repo, transfering issue

**Comment by gaby** [comment]
@jsorb84 Can you submit a PR to list your middleware on this repo under Third Party?
